name: publish

on:
  push:
    branches:
      - master


jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github context
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
            docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
            docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
            docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
